"""empty message

Revision ID: 1e74bc7464c9
Revises: b5a5b01a6efd
Create Date: 2022-10-12 22:04:39.995828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e74bc7464c9'
down_revision = 'b5a5b01a6efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('useless', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'useless')
    # ### end Alembic commands ###
