"""card user

Revision ID: 30666042f2a4
Revises: 9b894e353c0c
Create Date: 2022-11-12 21:58:12.714679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30666042f2a4'
down_revision = '9b894e353c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###
