"""add invoice

Revision ID: 356127333156
Revises: a205c535d47c
Create Date: 2022-11-27 18:38:02.866887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356127333156'
down_revision = 'a205c535d47c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
