"""card

Revision ID: 60269144dd97
Revises: 4a39cbaedb75
Create Date: 2022-11-05 00:00:17.804894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60269144dd97'
down_revision = '4a39cbaedb75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_photo', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=800), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
