"""empty message

Revision ID: 624217657b47
Revises: f57b8eca53b6
Create Date: 2022-10-12 23:21:15.100717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624217657b47'
down_revision = 'f57b8eca53b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
