"""add amount

Revision ID: a205c535d47c
Revises: 30666042f2a4
Create Date: 2022-11-27 18:31:47.239001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a205c535d47c'
down_revision = '30666042f2a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('current_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'current_amount')
    op.drop_column('cards', 'amount')
    # ### end Alembic commands ###
