"""empty message

Revision ID: b5a5b01a6efd
Revises: c516c2397e01
Create Date: 2022-10-12 22:04:04.120505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a5b01a6efd'
down_revision = 'c516c2397e01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
